config/routes.rb
Rails.application.routes.draw do
  get 'killer_categories/new'
  resources :jails do
    resources :killers, only: [:new, :create]
  end
  resources :killers, only: [:destroy, :show] do
  # resources :killers, only: [] do
    resources :killer_categories, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :killer_categories, dependent: :destroy
  has_many :killers, through: :killer_categories
end

app/models/jail.rb
# == Schema Information
#
# Table name: jails
#
#  id         :integer          not null, primary key
#  name       :string
#  banner_url :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Jail < ApplicationRecord
  validates :name, presence: true
  validates :banner_url, presence: true
  has_many :killers, dependent: :destroy
end

app/models/killer.rb
class Killer < ApplicationRecord
  belongs_to :jail
end

app/models/killer_category.rb
# == Schema Information
#
# Table name: killer_categories
#
#  id          :integer          not null, primary key
#  killer_id   :integer
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class KillerCategory < ApplicationRecord
  belongs_to :killer
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jails_controller.rb
class JailsController < ApplicationController
  before_action :set_jail, only: [:show, :edit, :update, :destroy]

  # GET /jails
  def index
    @jails = Jail.all
  end

  # GET /jails/1
  def show
    @killer = Killer.new
  end

  # GET /jails/new
  def new
    @jail = Jail.new
  end

  # GET /jails/1/edit
  def edit
  end

  # POST /jails
  def create
    @jail = Jail.new(jail_params)

    if @jail.save
      redirect_to @jail, notice: 'Jail was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /jails/1
  def update
    if @jail.update(jail_params)
      redirect_to @jail, notice: 'Jail was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /jails/1
  def destroy
    @jail.destroy
    redirect_to jails_url, notice: 'Jail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jail
      @jail = Jail.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def jail_params
      params.require(:jail).permit(:name, :banner_url)
    end
end

app/controllers/killer_categories_controller.rb
class KillerCategoriesController < ApplicationController
  def new
    @killer = Killer.find(params[:killer_id])
    @killer_category = KillerCategory.new
  end

  def create
    @killer = Killer.find(params[:killer_id])
    @killer_category = KillerCategory.new(killer_category_params)
    @killer_category.killer = @killer
    if @killer_category.save
      redirect_to jail_path(@killer.jail)
    else
      render :new
    end
  end

  private

  def killer_category_params
    params.require(:killer_category).permit(:category_id)
  end
end

app/controllers/killers_controller.rb
class KillersController < ApplicationController
  before_action :set_jail, only: [:new, :create]

  def new
    @killer = Killer.new
  end

  def create
    @killer = Killer.new(killer_params)
    @killer.jail = @jail
    if @killer.save
      redirect_to jail_path(@jail)
    else
      render :new
    end
  end

  def destroy
    killer = Killer.find(params[:id])
    killer.destroy
    redirect_to jail_path(killer.jail)
  end

  def show
  end

  private

  def killer_params
    params.require(:killer).permit(:name, :image_url)
  end

  def set_jail
    @jail = Jail.find(params[:jail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jails_helper.rb
module JailsHelper
end

app/helpers/killer_categories_helper.rb
module KillerCategoriesHelper
end

app/helpers/killers_helper.rb
module KillersHelper
end

app/views/jails/_form.html.erb
<%= simple_form_for(@jail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jails/edit.html.erb
<h1>Editing Jail</h1>

<%= render 'form', jail: @jail %>

<%= link_to 'Show', @jail %> |
<%= link_to 'Back', jails_path %>

app/views/jails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jails.each do |jail| %>
      <tr>
        <td><%= jail.name %></td>
        <td><%= jail.banner_url %></td>
        <td><%= link_to 'Show', jail %></td>
        <td><%= link_to 'Edit', edit_jail_path(jail) %></td>
        <td><%= link_to 'Destroy', jail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jail', new_jail_path %>

app/views/jails/new.html.erb
<h1>New Jail</h1>

<%= render 'form', jail: @jail %>

<%= link_to 'Back', jails_path %>

app/views/jails/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @jail.banner_url %>')">
  <h1><%= @jail.name %></h1>
</div>

<div class="container">
  <div class="row">
    <% @jail.killers.each do |killer| %>
      <div class="col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= killer.image_url %>');">
           <div class="card-tags">
            <% killer.categories.each do |category| %>
              <span>
                <%= category.name %>
              </span>
            <% end %>
          </div>

          <div class="card-description">
            <h2><%= killer.name %></h2>
          </div>
          <%= link_to "+", killer_path(killer), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/killer_categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h4>Add a category  for <%= @killer.name %></h4>
      <%= image_tag @killer.image_url, width: "200px" %>
      <%= simple_form_for [@killer, @killer_category] do |f| %>
        <%= f.association :category %>
        <%= f.submit "Add", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/killers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h1>Add prisoner</h1>
      <%= simple_form_for [@jail, @killer] do |f| %>
        <%= f.input :name, label: "Killer Name" %>
        <%= f.input :image_url %>
        <%= f.submit "Add", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/killers/show.html.erb
show.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prison</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>